//
// --------------------------------------------------------------------------
//  Gurux Ltd
// 
//
//
// Filename:        $HeadURL$
//
// Version:         $Revision$,
//                  $Date$
//                  $Author$
//
// Copyright (c) Gurux Ltd
//
//---------------------------------------------------------------------------
//
//  DESCRIPTION
//
// This file is a part of Gurux Device Framework.
//
// Gurux Device Framework is Open Source software; you can redistribute it
// and/or modify it under the terms of the GNU General Public License 
// as published by the Free Software Foundation; version 2 of the License.
// Gurux Device Framework is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
//
// This code is licensed under the GNU General Public License v2. 
// Full text may be retrieved at http://www.gnu.org/licenses/gpl-2.0.txt
//---------------------------------------------------------------------------

using System;
namespace Gurux.Service.Orm.Model
{
    /// <summary>
    /// Generic SQL column schema information.
    /// </summary>
    public sealed class GXColumnSchema
    {
        /// <summary>
        /// Column name.
        /// </summary>
        public string Name { get; set; } = "";

        /// <summary>
        /// Column ordinal position. First column is 1.
        /// </summary>
        public int Ordinal { get; set; }

        /// <summary>
        /// Native database type name.
        /// Examples: varchar, nvarchar, NUMBER, uuid, datetimeoffset.
        /// </summary>
        public string DbType { get; set; } = "";

        /// <summary>
        /// Generic .NET type, if known.
        /// Examples: typeof(string), typeof(int), typeof(Guid).
        /// </summary>
        public Type Type { get; set; }

        /// <summary>
        /// Maximum length for character or binary columns.
        /// Null if not applicable or unknown.
        /// </summary>
        public long? MaxLength { get; set; }

        /// <summary>
        /// Numeric precision.
        /// Example: decimal(18, 2) => 18.
        /// </summary>
        public int? Precision { get; set; }

        /// <summary>
        /// Numeric scale.
        /// Example: decimal(18, 2) => 2.
        /// </summary>
        public int? Scale { get; set; }

        /// <summary>
        /// Date/time fractional seconds precision.
        /// Example: datetime2(3) => 3.
        /// </summary>
        public int? DateTimePrecision { get; set; }

        /// <summary>
        /// True if NULL values are allowed.
        /// </summary>
        public bool IsNullable { get; set; }

        /// <summary>
        /// True if this column belongs to primary key.
        /// </summary>
        public bool IsPrimaryKey { get; set; }

        /// <summary>
        /// True if this column is unique.
        /// </summary>
        public bool IsUnique { get; set; }

        /// <summary>
        /// True if column value is generated by database.
        /// Examples: identity, auto_increment, generated always.
        /// </summary>
        public bool IsGenerated { get; set; }

        /// <summary>
        /// True if this is an identity or auto increment column.
        /// </summary>
        public bool IsIdentity { get; set; }

        /// <summary>
        /// True if this is an auto increment column.
        /// </summary>
        public bool IsAutoIncrement { get; set; }
        
        /// <summary>
        /// True if this column is computed from an expression.
        /// </summary>
        public bool IsComputed { get; set; }

        /// <summary>
        /// Default value expression as returned by database.
        /// </summary>
        public object? DefaultValue { get; set; }

        /// <summary>
        /// Computed column expression, if available.
        /// </summary>
        public string? ComputedExpression { get; set; }

        /// <summary>
        /// Column collation, if available.
        /// </summary>
        public string? Collation { get; set; }

        /// <summary>
        /// Column comment or description.
        /// </summary>
        public string? Comment { get; set; }


        public override string ToString()
        {
            return $"{Name} {DbType}";
        }
    }
}
